name: Artifacts demonstration

on: push

jobs:
  job_1:
    name: upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: "Create a local file"
        run: echo "Hi I am storing this" > file.txt

      - uses: actions/upload-artifact@v2
        with:
          name: file
          path: file.txt
          retention-days: 10


  job_2:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: file
      - run: cat file.txt
  